[package]
name = "sfrpg"
version = "0.1.0-alpha"
authors = ["DoctorVWA"]
edition = "2018"

[dependencies.druid]
git = "https://github.com/xi-editor/druid.git"
features = ["im"]

[dependencies.dnd5e]
path = "./systems/dnd5e"

[dependencies.ct]
path = "./systems/ct"
