[package]
name = "dnd5e"
version = "0.1.0"
authors = ["DoctorVWA"]
edition = "2018"

[dependencies.druid]
git = "https://github.com/xi-editor/druid.git"
features = ["im"]

[dependencies.json]
version = "0.12.4"
